/* ===========================================================================
   Which recordings exist, and under what name.

   GENERATED BY `scripts/build-samples.mjs`. Edit the spec in
   `samples.config.mjs` and re-run it; edits made here are overwritten.

   An empty array means "no sample on disk", which `lib/sfx.ts` reports as
   not-ready and the caller answers by playing its synthesised fallback.
   =========================================================================== */

/**
 * The cues that are pictures of real objects. Add a name here and in
 * `samples.config.mjs` together.
 */
export type SfxCue =
  /* The phone: a real motor on real wood, played twice per text by
     lib/found/buzz.ts. */
  "found-buzz";

export type SfxEntry = {
  /** Filenames under `/sfx/`. More than one is a round-robin — see `pick` in
   *  lib/sfx.ts. Empty means no recording yet. */
  readonly takes: readonly string[];
  /** Per-cue trim, applied on top of the caller's own level. */
  readonly gain: number;
  /** Whether this cue sustains under a gesture rather than firing once. */
  readonly sustained?: boolean;
};

/* @generated:start — scripts/build-samples.mjs rewrites everything below. */
export const SFX: Record<SfxCue, SfxEntry> = {
  "found-buzz": { takes: ["found-buzz-1.m4a", "found-buzz-2.m4a"], gain: 1 },
};
/* @generated:end */

export const CUES = Object.keys(SFX) as SfxCue[];
